eureka:
  client:
    service-url:
      defaultZone: http://discovery:8888/eureka/
    registry-fetch-interval-seconds: 3
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://mysql_container:3306/smsGateway
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: mysql
    show-sql: true
